name: Evening workout
on:
  schedule:
    - cron: '15 19 * * 1-6' #07:15PM UTC (08:15PM AMS time), Monday to Saturday
jobs:
  afternoonFlashcard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Evening workout message
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      run: bundle exec fastlane evening_workout_slack_message
