name: Morning workout
on:
  schedule:
    - cron: '30 4 * * 1-6' #04:30AM UTC (05:30AM AMS time), Monday to Saturday
jobs:
  afternoonFlashcard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Morning workout message
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        FL_POST_TO_SLACK_CHANNEL: ${{ secrets.FL_POST_TO_SLACK_CHANNEL }}
        SLACK_WORKSPACE_NAME: ${{ secrets.SLACK_WORKSPACE_NAME }}
      run: bundle exec fastlane morning_workout_slack_message
