name: Morning workout
on:
  schedule:
    - cron: '45 2 * * *' #02:45AM UTC (04:45AM AMS time), Every day
jobs:
  morningWorkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Configure Git
      run: |
        git config --local user.email "i.am.manish.rathi@gmail.com"
        git config --local user.name "Manish Rathi"
    - name: Morning workout message
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        FL_POST_TO_SLACK_CHANNEL: ${{ secrets.FL_POST_TO_SLACK_CHANNEL }}
        SLACK_WORKSPACE_NAME: ${{ secrets.SLACK_WORKSPACE_NAME }}
      run: bundle exec fastlane morning_workout_slack_message
